[build]
publish = "siteContent/public"
command = "cd siteContent && hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.79.1"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "cd siteContent &&  hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
